vich_uploader:
    db_driver: orm

    mappings:
       biens_images:
           uri_prefix: '%app.path.biens_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.biens_images%'
